名称：获取和合并电视源

on:
  schedule:
-cron：'02,14****'#每天北京时间 10 22你是怎么看的
workflow_dispatch:#开启手动触发按钮

jobs:
  build:
运行：ubuntu-最新
    steps:
- name: Checkout repository
用途：actions/checkout@v3

-名称：获取和合并URL
运行：|
        echo "开始抓取合并..."
#清空或创建 live.txt
> live.txt
        
        # 抓取1 (GitHub网络畅通，直接抓)
echo“正在抓取 pllive. txt……”
curl -sL "https://raw.githubusercontent.com/jn950/live/main/tv/pllive.txt" >> live.txt
        
#抓取 2（GitHub you you you IPv6，you koo666. online）
echo“正在抓取 koo66650085……”
curl -sL "http://koo666.online:50085/sub?nFMW1pnS=txt" >> live.txt
        
echo“正在抓取 koo 66551666……”
curl -sL "http://koo666.online:51666" >> live.txt
        
echo“正在抓取 koo 665508……”
curl -sL "http://koo666.online:5908" >> live.txt
        
        echo "抓取合并完成！"

-name：提交并推送更改
运行：|
git config --global user.name "GitHub Action"
git config --global user.email "action@github.com"
git add live.txt
git diff --staged --quiet || git commit -m "Auto update live.txt"
推送至 git 仓库
